dependencies:
  bblanchon/arduinojson:
    version: "7.4.2"
  esphome/esp-audio-libs:
    version: 2.0.3
  espressif/esp-tflite-micro:
    version: 1.3.3~1
  espressif/esp32-camera:
    version: 2.1.1
  espressif/mdns:
    version: 1.9.1
  espressif/esp_wifi_remote:
    version: 1.3.2
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/eppp_link:
    version: 1.1.4
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/esp_hosted:
    version: 2.11.5
    rules:
      - if: "target in [esp32h2, esp32p4]"
  zorxx/multipart-parser:
    version: 1.0.1
  espressif/lan867x:
    version: "2.0.0"
    rules:
      - if: "target in [esp32, esp32p4]"
  espressif/esp_tinyusb:
    version: "1.7.6~1"
    rules:
      - if: "target in [esp32s2, esp32s3, esp32p4]"
  esphome/esp-hub75:
    version: 0.3.2
    rules:
      - if: "target in [esp32, esp32s2, esp32s3, esp32c6, esp32p4]"
  esp32async/asynctcp:
    version: 3.4.91
