---
name: Synchronise Device Classes from Home Assistant

on:
  workflow_dispatch:
  schedule:
    - cron: "45 6 * * *"

jobs:
  sync:
    name: Sync Device Classes
    runs-on: ubuntu-latest
    if: github.repository == 'esphome/esphome'
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Checkout Home Assistant
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: home-assistant/core
          path: lib/home-assistant

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.13

      - name: Install Home Assistant
        run: |
          python -m pip install --upgrade pip
          pip install -e lib/home-assistant
          pip install -r requirements_test.txt pre-commit

      - name: Sync
        run: |
          python ./script/sync-device_class.py

      - name: Run pre-commit hooks
        run: |
          python script/run-in-env.py pre-commit run --all-files

      - name: Commit changes
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: "Synchronise Device Classes from Home Assistant"
          committer: esphomebot <esphome@openhomefoundation.org>
          author: esphomebot <esphome@openhomefoundation.org>
          branch: sync/device-classes
          delete-branch: true
          title: "Synchronise Device Classes from Home Assistant"
          body-path: .github/PULL_REQUEST_TEMPLATE.md
          token: ${{ secrets.DEVICE_CLASS_SYNC_TOKEN }}
